# application-prod.yml
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.example.product: INFO
    org.springframework.web: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics